export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
export const CART_EMPTY = 'CART_EMPTY';